[package]
name = "actix_hello_world"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Step 1
actix-web = "2.0.0"
actix-rt = "1.0.0"
#step 7
dotenv = "0.15.0"